# Generated by Django 3.2.7 on 2021-09-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0003_alter_image_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='user_followers', to='gram.Follow'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='user_following', to='gram.Follow'),
        ),
    ]
