# Generated by Django 3.2.7 on 2021-09-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0007_auto_20210913_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.ManyToManyField(blank=True, to='gram.Profile'),
        ),
    ]
